### ISSUE TITLE
Unable to detect camera in iOS , modeller version 7.17.2

### ISSUE THREAD

**Issue by NTcoder** [mendix/CameraWidgetForPhoneGap#34] opened 2018-08-31 09:03 UTC
This widget does not work on mendix modeller version 7.17.2 on iOS.

It shows, unable to detect camera.

**Comment by jseremba** [comment] 2018-09-03 09:07
Dear @navadiatarun thanks for reporting this issue, we'll look into it and gt back to you as soon as possible.
Cheers
Joseph

**Comment by jseremba** [comment] 2018-09-03 13:29
@navadiatarun kindly confirm whether this issue occurs on the web or phonegap app else its a duplicate of #31

**Comment by navadiatarun** [comment] 2018-09-03 13:38
It happens in ios, ipad only. Works on android.

**Comment by jseremba** [comment] 2018-09-04 12:30
@navadiatarun we were unable to reproduce the issue on ios ipad as you stated but kindly confirm whether it occurs on web or PhonaGap app or share steps to reproduce.

**Comment by navadiatarun** [comment] 2018-09-14 04:45
This issue is occurring on the latest version of the modeller on iPad. create a sample project, add a mobile navigation page containing this widget, build the project and the mobile app and reproduce.

This does not occur on web and this widget is not intended to use there also.

**Comment by Andries-Smit** [comment] 2019-05-09 11:10
Dear @NTcoder 

One of the issue of the past, is the new require permission description on iOS. This was resolved in the newer version of the hybrid app.

https://github.com/mendix/hybrid-app-base/commit/6ac676d59f9f5b090950654903f23c3575e70647

If it still persists please open a ticket at support.mendix.com and provide a simplified test project, PhoneGap bundle, iPad version. and steps to reproduce the issue.

Cheers, Andries

**Closed by Andries-Smit** 2019-05-09 11:10 UTC
